# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.0.29
_src_path: git+https://stefanschuhart@bitbucket.org/geowerkstatt-hamburg/python_project_template
author_email: stefan.schuhart@gv.hamburg.de
author_fullname: StefanSchuhart
author_git_username: StefanSchuhart
create_global_environment: false
create_project_environment: false
docker_image_distribution: bookworm
initial_commit: false
is_datascience_project: false
package_manager: poetry
project_description: just some exmaples
project_name: example_ogcapi_processes
python_package_distribution_name: example-ogcapi-processes
python_package_import_name: example_ogcapi_processes
python_version: '3.11'
repository_namespace: geowerkstatt-hamburg
repository_provider: bitbucket.org
