secrets:
  MY_SECRET1:
    file: ./secrets/my_secret_1.txt

services:
  app:
    image: ${CONTAINER_REGISTRY}/analytics/${IMAGE_NAME}:${IMAGE_TAG}
    restart: "unless-stopped"
    environment:
      PYGEOAPI_SERVER_PORT: ${PYGEOAPI_SERVER_PORT}
      PYGEOAPI_SERVER_PORT_CONTAINER: ${PYGEOAPI_SERVER_PORT_CONTAINER}
      PYGEOAPI_CONFIG: /home/pythonuser/pygeoapi-config.yml
      PYGEOAPI_OPENAPI: /home/pythonuser/pygeoapi-openapi.yml
      PYGEOAPI_SERVER_HOST: localhost
    volumes:
      - ${PYGEOAPI_CONFIG}:/home/pythonuser/pygeoapi-config.yml
      - ${PYGEOAPI_OPENAPI}:/home/pythonuser/pygeoapi-openapi.yml
    ports:
      - ${PYGEOAPI_SERVER_PORT_CONTAINER}:${PYGEOAPI_SERVER_PORT}
    command: [
      '/bin/bash', '-c',
      'pygeoapi openapi generate /home/pythonuser/pygeoapi-config.yml --output-file /home/pythonuser/pygeoapi-openapi.yml && pygeoapi serve --flask'
    ]
