version: "3.7"

services:
  app:
    image: ${CONTAINER_REGISTRY}/analytics/${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_COMMIT:

  commandline-app:
    image: ${CONTAINER_REGISTRY}/analytics/${IMAGE_NAME}-cmd:${IMAGE_TAG}
    build:
      context: .
      dockerfile: cmd.Dockerfile
      args:
        SOURCE_COMMIT:
