secrets:
  MY_SECRET1:
    file: ./secrets/my_secret_1.txt

services:
  app:
    image: ${CONTAINER_REGISTRY}/analytics/${IMAGE_NAME}:${IMAGE_TAG}
    restart: "unless-stopped"
    ports:
      - ${PYGEOAPI_SERVER_PORT_CONTAINER}:${PYGEOAPI_SERVER_PORT}
    command: ['src/app.py']
